- name: create rg
  hosts: localhost
  connection: local
  
  tasks:
    - name: Creating resource group - "{{ resource_group }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg
